
import React from 'react';
import { ImageIcon, SpinnerIcon } from './Icons';

interface ImageDisplayProps {
    imageUrl: string | null;
    isLoading: boolean;
}

const ImageDisplay: React.FC<ImageDisplayProps> = ({ imageUrl, isLoading }) => {
    return (
        <div className="relative w-full aspect-square bg-gray-800/50 rounded-lg shadow-lg flex items-center justify-center border border-gray-700 overflow-hidden">
            {isLoading && (
                <div className="absolute inset-0 bg-black/50 flex flex-col items-center justify-center z-10">
                    <SpinnerIcon />
                    <p className="mt-4 text-lg text-gray-300">Creando magia...</p>
                </div>
            )}
            {!isLoading && !imageUrl && (
                <div className="text-center text-gray-500 flex flex-col items-center">
                    <ImageIcon />
                    <p className="mt-4 text-lg">La imagen generada aparecerá aquí</p>
                </div>
            )}
            {imageUrl && (
                <img
                    src={imageUrl}
                    alt="Generated by AI"
                    className="w-full h-full object-contain transition-opacity duration-500 animate-fade-in"
                />
            )}
            <style>{`
                @keyframes fade-in {
                    from { opacity: 0; }
                    to { opacity: 1; }
                }
                .animate-fade-in {
                    animation: fade-in 0.5s ease-in-out;
                }
            `}</style>
        </div>
    );
};

export default ImageDisplay;
